## Векторы и матрицы

### Массив Numpy (Numpy array)

In [2]:
import numpy as np

In [ ]:
# предположим мы записали данные
# роста, веса и обхвата шеи одного человека в список
data = [1.72, 54, 36.2]

In [ ]:
# убедимся, что это список с помощью функции type()
type(data)

list

In [ ]:
# преобразуем список в массив Numpy
data_Numpy = np.array(data)
data_Numpy

array([ 1.72, 54.  , 36.2 ])

In [ ]:
# если у нас несколько наблюдений, то нужна матрица, т.е.
# по сути, несколько векторов
data_matrix = np.array([[1.72, 54, 36.2], [1.74, 58, 36.3], [1.68, 52, 32.9]])
data_matrix

array([[ 1.72, 54.  , 36.2 ],
       [ 1.74, 58.  , 36.3 ],
       [ 1.68, 52.  , 32.9 ]])

In [ ]:
# мы можем посмотреть размерность матрицы (количество строк и столбцов)
data_matrix.shape

(3, 3)

### Скалярное произведение векторов (dot product)


  $$\textbf{a}=(a_{1}, a_{2})$$
  $$\textbf{w}=(w_{1}, w_{2})$$
  $$\textbf{a}\cdot\textbf{w}=a_{1}w_{1}+a_{2}w_{2}$$

In [ ]:
# даны два вектора в виде массивов Numpy

a = np.array([1.72, 54]) # вектор данных
w = np.array([19.86, 0.05]) # вектор весов

In [ ]:
# перемножим их вручную
1.72 * 19.86 + 54 * 0.05

36.8592

In [ ]:
# используем скалярное произведение векторов
np.dot(a, w)

36.8592

### Косинусное сходство между векторами

Первый шаг: найдем косинус угла по формуле $$ \cos \theta ={\mathbf {b} \cdot \mathbf {c} \over \|\mathbf {b} \|\|\mathbf {c} \|} $$

In [ ]:
# даны два вектора (данные двух человек)
# нам нужно понять, насколько они схожи
b = np.array([1.72, 54, 36.2])
c = np.array([1.56, 47, 30.0])

In [ ]:
# вначале выполним операции в числителе формулы
numerator = np.dot(b, c)

In [ ]:
# теперь займемся знаменателем и
# (1) рассчитаем длины (по большому счету, это теорема Пифагора)
bLen = np.linalg.norm(b)
cLen = np.linalg.norm(c)

# (2) перемножим их
denominator = bLen * cLen

In [ ]:
# посмотрим, чему равен косинус угла между векторами
cosine = numerator/denominator
cosine

0.9997468709497721

Второй шаг: найдем угол в градусах по его косинусу

In [ ]:
# для этого вначале вычислим угол в радианах
angle_radians = np.arccos(cosine)

# затем в градусах
angle_degrees = angle_radians * 360/2/np.pi

In [ ]:
angle_degrees

1.2891925481394304

### Упражнения

In [3]:
# даны два вектора
v1 = np.array([37, 84, 110.2, 18.6])
v2 = np.array([5, 36, 199.6, 5.1])

#### Основы работы с массивами

**Задание 1**. Посмотрите с помощью Питона на тип данных любого из двух векторов.

In [4]:
v1

array([ 37. ,  84. , 110.2,  18.6])

**Задание 2**. Какая размерность у этих векторов?

In [6]:
print(v1.shape)
print(v2.shape)

(4,)
(4,)


#### Скалярное произведение векторов

**Задание 3**. Перемножьте векторы `v1` и `v2` вручную.

In [8]:
37 * 5 + 84 * 36 + 110.2 * 199.6 + 18.6 * 5.1


25299.78

**Задание 4**. Используйте функцию **dot()**.

In [10]:
 numr = np.dot(v1, v2)
 numr

25299.78

#### Косинусное сходство между векторами

**Задание 5**. Найдите угол в градусах между векторами `v1` и `v2`.

In [13]:
v1_len = np.linalg.norm(v1)
v2_len = np.linalg.norm(v2)

denom = v1_len * v2_len

coss = numr/denom

angle_rad = np.arccos(coss)
angle_deg = angle_rad * 360/2/np.pi
angle_deg

30.458206946879134